name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./CounterApp/CounterApp.csproj

    - name: Build
      run: dotnet build ./CounterApp/CounterApp.csproj --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test ./CounterApp/CounterApp.csproj --no-build --verbosity normal
